import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import {
  ApolloNextAppProvider,
} from "@apollo/experimental-nextjs-app-support/ssr";
import { makeClient } from '@/services/apollo-client'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloNextAppProvider makeClient={makeClient}>
          {children}
        </ApolloNextAppProvider>
      </body>
    </html>
  )
}
